---@class UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType : System.Enum
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType = {}
---@type UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType
CS.UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType = UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType

---@return System.Int32 value:0
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.Metadata_Version = 0
---@return System.Int32 value:1
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.Metadata_RecordDate = 1
---@return System.Int32 value:2
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.Metadata_UserMetadata = 2
---@return System.Int32 value:3
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.Metadata_CaptureFlags = 3
---@return System.Int32 value:4
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.Metadata_VirtualMachineInformation = 4
---@return System.Int32 value:5
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeTypes_Name = 5
---@return System.Int32 value:6
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeTypes_NativeBaseTypeArrayIndex = 6
---@return System.Int32 value:7
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeObjects_NativeTypeArrayIndex = 7
---@return System.Int32 value:8
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeObjects_HideFlags = 8
---@return System.Int32 value:9
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeObjects_Flags = 9
---@return System.Int32 value:10
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeObjects_InstanceId = 10
---@return System.Int32 value:11
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeObjects_Name = 11
---@return System.Int32 value:12
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeObjects_NativeObjectAddress = 12
---@return System.Int32 value:13
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeObjects_Size = 13
---@return System.Int32 value:14
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeObjects_RootReferenceId = 14
---@return System.Int32 value:15
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.GCHandles_Target = 15
---@return System.Int32 value:16
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.Connections_From = 16
---@return System.Int32 value:17
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.Connections_To = 17
---@return System.Int32 value:18
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.ManagedHeapSections_StartAddress = 18
---@return System.Int32 value:19
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.ManagedHeapSections_Bytes = 19
---@return System.Int32 value:20
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.ManagedStacks_StartAddress = 20
---@return System.Int32 value:21
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.ManagedStacks_Bytes = 21
---@return System.Int32 value:22
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.TypeDescriptions_Flags = 22
---@return System.Int32 value:23
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.TypeDescriptions_Name = 23
---@return System.Int32 value:24
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.TypeDescriptions_Assembly = 24
---@return System.Int32 value:25
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.TypeDescriptions_FieldIndices = 25
---@return System.Int32 value:26
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.TypeDescriptions_StaticFieldBytes = 26
---@return System.Int32 value:27
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.TypeDescriptions_BaseOrElementTypeIndex = 27
---@return System.Int32 value:28
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.TypeDescriptions_Size = 28
---@return System.Int32 value:29
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.TypeDescriptions_TypeInfoAddress = 29
---@return System.Int32 value:30
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.TypeDescriptions_TypeIndex = 30
---@return System.Int32 value:31
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.FieldDescriptions_Offset = 31
---@return System.Int32 value:32
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.FieldDescriptions_TypeIndex = 32
---@return System.Int32 value:33
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.FieldDescriptions_Name = 33
---@return System.Int32 value:34
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.FieldDescriptions_IsStatic = 34
---@return System.Int32 value:35
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeRootReferences_Id = 35
---@return System.Int32 value:36
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeRootReferences_AreaName = 36
---@return System.Int32 value:37
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeRootReferences_ObjectName = 37
---@return System.Int32 value:38
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeRootReferences_AccumulatedSize = 38
---@return System.Int32 value:39
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeAllocations_MemoryRegionIndex = 39
---@return System.Int32 value:40
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeAllocations_RootReferenceId = 40
---@return System.Int32 value:41
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeAllocations_AllocationSiteId = 41
---@return System.Int32 value:42
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeAllocations_Address = 42
---@return System.Int32 value:43
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeAllocations_Size = 43
---@return System.Int32 value:44
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeAllocations_OverheadSize = 44
---@return System.Int32 value:45
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeAllocations_PaddingSize = 45
---@return System.Int32 value:46
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeMemoryRegions_Name = 46
---@return System.Int32 value:47
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeMemoryRegions_ParentIndex = 47
---@return System.Int32 value:48
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeMemoryRegions_AddressBase = 48
---@return System.Int32 value:49
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeMemoryRegions_AddressSize = 49
---@return System.Int32 value:50
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeMemoryRegions_FirstAllocationIndex = 50
---@return System.Int32 value:51
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeMemoryRegions_NumAllocations = 51
---@return System.Int32 value:52
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeMemoryLabels_Name = 52
---@return System.Int32 value:53
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeAllocationSites_Id = 53
---@return System.Int32 value:54
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeAllocationSites_MemoryLabelIndex = 54
---@return System.Int32 value:55
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeAllocationSites_CallstackSymbols = 55
---@return System.Int32 value:56
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeCallstackSymbol_Symbol = 56
---@return System.Int32 value:57
UnityEditorInternal.Profiling.Memory.Experimental.FileFormat.EntryType.NativeCallstackSymbol_ReadableStackTrace = 57

