---@class MID
MID = {}
local MID = MID

MID.UI_SHOW_BEGIN = 0
MID.UI_OPEN = 1
MID.UI_CLOSE = 2
MID.GAME_RESUME = 3
MID.LOGIN_ACCOUNT_BEGIN = 4
MID.LOGIN_ACCOUNT_SUCCESS = 5
MID.LOGIN_ACCOUNT_FAIL = 6
MID.REALNAME_VERIFIED = 7
MID.ACCOUNT_BIND_RESULT = 8

MID.NETWORK_CHANGED = 10
MID.ENTER_GAME_RUNNING = 11
MID.DOWNLOAD_STRATEGY_PROGRESS = 12
MID.LOAD_DATA_FINISH = 13

MID.NET_CONNECTED = 20
MID.NET_DISCONNECTED = 21
MID.NET_CONNECT_ERROR = 22
MID.NET_RECONNECTED = 23

MID.GUIDE_TRIGGER = 50

MID.SYS_OPEN = 60
MID.SYS_OPEN_REFRESH = 61

MID.ITEM_NUM_UPDATE = 100

MID.BATTLE_HP_CHAGED = 105
MID.UI_POP_DAMAGE_SET_CHANGED = 106
MID.BATTLE_ENEMY_DEAD = 107
MID.BATTLE_FLY_GOLD = 108
MID.BATTLE_LV_CHANGE = 109
MID.BATTLE_START_UI_SHOW_END = 110
MID.BATTLE_CHAPTER_FINISH = 111
MID.BATTLE_UPDATE_EXP = 112
MID.BATTLE_ROLE_LV = 113
MID.BATTLE_UPDATE_ENERGY = 114
MID.BATTLE_ENEMY_NUM_CHANGE = 115
MID.BATTLE_ENEMY_SPAWN = 116
MID.BATTLE_PLAYER_REVIVAL = 117
MID.BATTLE_PLAYER_DEAD = 118
MID.BATTLE_SPAWN_WARNING = 119
MID.BATTLE_SHIELD_CHAGED = 120
MID.BATTLE_GAIN_GENIUS = 121
MID.BATTLE_DROP_ITEMS = 122
MID.BATTLE_SCENE_ITEM_DEAD = 123
MID.HERO_KILL_ENEMY = 124
MID.BATTLE_MAIN_SKILL_DURATION = 126
MID.BATTLE_SHIELD_BAN = 127
MID.BATTLE_HERO_ENTER_BATTLE = 128
MID.BATTLE_BOSS_DEAD_END = 129
MID.BATTLE_ADD_BUFF = 130
MID.BATTLE_REMOVE_BUFF = 131
MID.BATTLE_ENEMY_DAMAGE = 132
MID.BATTLE_HERO_COMBO_UPDATE = 133
MID.BATTLE_ENTER_REWARD_LEVEL = 134
MID.BATTLE_EXIT_REWARD_LEVEL = 135
MID.BATTLE_SHOW_DROP_BUFF = 136
MID.BATTLE_BATTLE_TIMER_PAUSE = 137


MID.BATTLE_LEVEL_START = 500
MID.BATTLE_LEVEL_END = 501
MID.BATTLE_LEVEL_PASS = 502
MID.BATTLE_LEVEL_FAIL = 503
MID.BATTLE_ENTITY_DELETED = 504
MID.BATTLE_HERO_LOAD_FINISH = 505
MID.BATTLE_HERO_DESTROY = 506
MID.BATTLE_ENEMY_BORN_OVER = 507

-----------------------------------UIBase-----------------------------------
MID.SHOW_LOWER_UI = 550
MID.HIDE_LOWER_UI = 551
MID.BAN_COMBAT_BTN_CLICK = 552

MID.ON_OPEN_MENU = 553
MID.ON_CLOSE_MENU = 554
-----------------------------------UIBase-----------------------------------