local cmd_name_map = {
    "GuestLoginReq",
    "GuestLoginRes",
    "Relogin",
    "UserLostConn",
    "EditProfileReq",
    "EditProfileRes",
    "AccountUpgradeReq",
    "AccountUpgradeRes",
    "UnameLoginReq",
    "UnameLoginRes",
    "LoginOutReq",
    "LoginOutRes",
    "GetUgameInfoReq",
    "GetUgameInfoRes",
    "RecvLoginBonuesReq",
    "RecvLoginBonuesRes",
    "GetWorldRankUchipReq",
    "GetWorldRankUchipRes",
    "GetSysMsgReq",
    "GetSysMsgRes",
    "LoginLogicReq",
    "LoginLogicRes",
}

return cmd_name_map